---
title: 'Stat 469 Assignment #4 Ian Sam'
author: "Ian Sam"
date: "2025-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
load("assignment4_data.rda")

# Log transformation
bulk_log <- log1p(bulk)

# Patient clustering
hc_original <- hclust(dist(t(bulk)), method = "complete")
hc_log <- hclust(dist(t(bulk_log)), method = "complete")

# K-means clustering (on genes)
k_list <- c(20, 30, 40)
kmeans_results_original <- lapply(k_list, function(k) kmeans(bulk, centers = k, nstart = 100))
kmeans_results_log <- lapply(k_list, function(k) kmeans(bulk_log, centers = k, nstart = 100))

# Plotting function with patient dendrogram, heatmap, and labeled color scale
plot_heatmap <- function(data_matrix, hc_patients, kmeans_genes, k_value, is_log) {
  patient_order <- hc_patients$order
  gene_order <- order(kmeans_genes$cluster)
  reordered_matrix <- data_matrix[gene_order, patient_order]

  # Set layout: dendrogram (1), heatmap (2), color scale (3)
  layout(matrix(c(1, 2, 3), ncol=1), heights=c(1, 5, 1))

  # Dendrogram (top)
  par(mar=c(0, 5, 2, 2))
  plot(as.dendrogram(hc_patients), horiz=FALSE, xaxt='n', main="", ylab="", xlab="", sub="")

  # Heatmap (middle)
  par(mar=c(2, 5, 2, 2))
  image(t(reordered_matrix), col=heat.colors(100), axes=FALSE,
        main=paste0("Heatmap (K=", k_value, ", ", ifelse(is_log, "Log", "Original"), ")"))
  axis(1, at=seq(0, 1, length.out=ncol(reordered_matrix)), labels=FALSE)
  axis(2, at=seq(0, 1, length.out=nrow(reordered_matrix)), labels=FALSE)

  # Add gene cluster boundaries
  cluster_labels <- kmeans_genes$cluster[gene_order]
  gene_boundaries <- which(diff(cluster_labels) != 0) / nrow(reordered_matrix)
  abline(h = gene_boundaries, col = "black", lwd = 1.5)

  # Color scale (bottom)
  par(mar=c(3, 5, 1, 2))
  image(1:100, 1, as.matrix(1:100), col=heat.colors(100), axes=FALSE, xlab="", ylab="")
  axis(1, at=c(1, 50, 100), labels=c("Low", "Medium", "High"))
  box()
}

# Generate all 6 heatmaps
for (i in seq_along(k_list)) {
  k_val <- k_list[i]

  # Original data
  plot_heatmap(bulk, hc_original, kmeans_results_original[[i]], k_val, is_log = FALSE)

  # Log-transformed data
  plot_heatmap(bulk_log, hc_log, kmeans_results_log[[i]], k_val, is_log = TRUE)
}


```

